server:
  port: 8080  servlet:    session:      tracking-modes:      - cookie    encoding:      force: true

spring:
  datasource:
    url: jdbc:postgresql://192.168.145.129:5432/postgres
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    
    
    
    
    
mybatis:
  type-aliases-package: com.jwland.*
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:com.jwland.mapper.**.xml
  
#login-id: test01
#login-password: 1q1q1q
login-id: "admin"
login-password: "0000"
